id: P006854
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18985
  title: 'དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཆོས་སྐོར། '
  author: ''
  volumes:
    291405383a134f63afd6f7dd3a5b76d2:
      image_group_id: I8LS18987
      title: ''
      volume_number: 1
      total_pages: 630
      base_file: v001.txt
